[package]
name = "substreams-abis"
version = "0.5.4"
description = "Substreams ABIs"
license = "MIT"
edition = "2021"
authors = ["Denis <denis@pinax.network>"]

[lib]
crate-type = ["rlib"]

[dependencies]
ethabi = "18.0"
substreams = "0.6.4"
substreams-ethereum = "0.10.6"
num-bigint = "0.4"

[build-dependencies]
prost-build = "0.14.1"
anyhow = "1"
substreams-ethereum = "0.10"
walkdir = "2"
